version: '3.1'
services:
  mongo:
    image: mongo
    container_name: 'mongo-graphql-server'
    restart: always
#    volumes:
#      - ./mongo/:/data/db
    environment:
      MONGO_INITDB_DATABASE: graphql-server
    ports:
      - 27017:27017